export default  {
    products:[
        {
        name:'Laptop',
        category:'laptop',
        image:'/images/laptop/L1.jpg',
        price:474,
        brand:'Dell',
        rating:4.5,
        numReviews:10
       },
    {
        name:'Laptop',
        image:'/images/laptop/L2.jpg',
        price:474,
        brand:'Dell',
        rating:4.5,
        numReviews:10 
},
{
    name:'Laptop',
    image:'/images/laptop/L1.jpg',
    price:474,
    brand:'Dell',
    rating:4.5,
    numReviews:10
}]
}